/*
 * File: app/model/DossierModel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Plato.model.Dossier', {
    extend: 'Ext.data.Model',
    fields: [
        {
            name: 'committeeDossier'
        },
        {
            name: 'procedureNumber'
        },
        {
        	name: 'title'
        },
        {
            name: 'rapporteurWithGroup'
        },
        {
            name: 'administratorResponsible'
        },
        {
            name: 'referenceDocument'
        },
        {
            name: 'mainOpinion'
        },
        {
            name: 'nameOfMainOpinionCommittee'
        },
        {
            name: 'workingDocument'
        },
        {
            name: 'exchangeOfView'
        },
        {
            name: 'PRorPATranslationSubmission'
        },
        {
            name: 'PRorPATranslationDeadline'
        },
        {
            name: 'PRorPAConsiderationInCommittee'
        },
        {
            name: 'PRorPAFDR'
        },
        {
            name: 'PRorPAFDRreplacesFdr'
        },
        {
            name: 'PRorPApeNumber'
        },
        {
            name: 'PRorPAsourcelanguage'
        },
        {
            name: 'AMTablingDeadline'
        },
        {
            name: 'AMTranslationSubmission'
        },
        {
            name: 'AMTranslationDeadline'
        },
        {
            name: 'AMFDR'
        },
        {
            name: 'AMFDRreplacesFdr'
        },
        {
            name: 'AMpeNumber'
        },
        {
            name: 'AMsourcelanguage'
        },
        {
            name: 'voteInCommittee'
        },
        {
            name: 'RRorADTranslationSubmission'
        },
        {
            name: 'RRorADTranslationDeadline'
        },
        {
            name: 'RRorADFDR'
        },
        {
            name: 'RRorADFDRreplacesFdr'
        },
        {
            name: 'RRorADpeNumber'
        },
        {
            name: 'RRorADsourcelanguage'
        },
        {
            name: 'reading'
        },
        {
            name: 'iterPhase'
        }/*,
        {
            name: 'keywords'
        }*/,
        {
            name: 'plenaryVote'
        } 
    ]
});